name: flatex
description: "Math equation rendering for Flutter App based on LaTeX"
version: 1.0.0
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # Add assets section to include the fonts directory
  assets:
    - fonts/
  
  fonts:
    - family: Xits
      fonts:
        - asset: fonts/Xits/xits-math.otf
    - family: LatinModern
      fonts:
        - asset: fonts/LatinModern/latinmodern-math.otf
    - family: Libertinus
      fonts:
        - asset: fonts/Libertinus/LibertinusMath-Regular.otf
    - family: Fira
      fonts:
        - asset: fonts/Fira/FiraMath-Regular.otf
    - family: Garamond
      fonts:
        - asset: fonts/Garamond/garamond-math.otf
    - family: Texgyretermes
      fonts:
        - asset: fonts/Texgyretermes/texgyretermes-math.otf
    - family: Euler
      fonts:
        - asset: fonts/Euler/Euler-Math.otf
    - family: Lete
      fonts:
        - asset: fonts/Lete/LeteSansMath.otf
    - family: Kp
      fonts:
        - asset: fonts/Kp/KpMath-Light.otf
        - asset: fonts/Kp/KpMath-Sans.otf
          style: normal
          weight: 400
